name: Java CI

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # Eller annan distribution som stöder Java 21 jupp
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{  hashFiles('**/pomxml') }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run program
        run: java -cp target/spring_mysql_api-0.0.1-SNAPSHOT.jar com.example.spring_mysql_api.SpringMysqlApiApplication > output.txt
      - name: Upload output
        uses: actions/upload-atifact@v4
        with:
          name: output-log
          path: output.txt